feat(volunteer): add all volunteer's pages + fix(student): finish and…
RomainDECOSTER/rom2-front pull request #7
Opened 2021-04-10 14:41 UTC by FoucaultChdr

add all volunteer's pages + fix(student): finish and fix student profil page

2021-04-11 09:30 UTC, RomainDECOSTER requested changes

2021-04-11 09:30 UTC, RomainDECOSTER commented on src/components/ComonProfil/AvailabilitiesProfil.jsx
> +  const weekDay = moment.weekdays(true).map(day => {
Cette variable n'est pas utilisée si ?

2021-04-11 09:30 UTC, RomainDECOSTER commented on src/scenes/Volunteer/VolunteerCreate.jsx
> +    StudentUtils.getStudentTemplates().then(templates => {
Tu es dans les volunteer et tu appelles le StudentUtils ?

2021-04-11 09:30 UTC, RomainDECOSTER commented on src/scenes/Volunteer/VolunteerEdit.jsx
> +    Promise.all([loadInfos(), StudentUtils.getStudentTemplates()]).then(([values, templates]) => {
Idem

2021-04-11 09:30 UTC, RomainDECOSTER commented on src/services/volunteer/actioner.js
> +        toast.error(messages.unableToRetrieveStudentList);
Il faut créer un message d'erreur pour les volunteer

2021-04-11 09:30 UTC, RomainDECOSTER commented on src/services/volunteer/actioner.js
> +        toast.error(messages.unableToRetrieveStudentList);
idem

2021-04-11 09:35 UTC, FoucaultChdr commented on src/scenes/Volunteer/VolunteerCreate.jsx
> +    StudentUtils.getStudentTemplates().then(templates => {
La fonction est un Utils pour recuperer les workshops et les campagnes

2021-04-11 09:50 UTC, RomainDECOSTER commented on src/scenes/Volunteer/VolunteerCreate.jsx
> +    StudentUtils.getStudentTemplates().then(templates => {
Yes mais elle est dans le utils des students et la tu es dans les volunteer. Donc soit elle est pas au bon endroit soit il faut créer un utils pour les volunteer

2021-04-11 09:59 UTC, RomainDECOSTER commented on src/scenes/Volunteer/VolunteerEdit.jsx
> +    Promise.all([loadInfos(), StudentUtils.getStudentTemplates()]).then(([values, templates]) => {
TEST Discord notif

2021-04-11 10:00 UTC, FoucaultChdr commented on src/scenes/Volunteer/VolunteerCreate.jsx
> +    StudentUtils.getStudentTemplates().then(templates => {
J'ai creer un dossier comon pour mettre l'utils dedans

2021-04-11 10:01 UTC, RomainDECOSTER commented on src/scenes/Volunteer/VolunteerCreate.jsx
> +    StudentUtils.getStudentTemplates().then(templates => {
Parfait

2021-04-13 07:21 UTC, RomainDECOSTER approved these changes

2021-04-13 07:21 UTC, merged