Feature/interview
RomainDECOSTER/rom2-front pull request #9
Opened 2021-04-17 19:51 UTC by FoucaultChdr

All content about interviews.

2021-04-19 13:30 UTC, RomainDECOSTER requested changes

2021-04-19 13:30 UTC, RomainDECOSTER commented on src/scenes/Home/components/InterviewDialogBox.jsx
> +                className="bosch-sensor-edit-button"
Cette class existe ?

2021-04-19 13:30 UTC, RomainDECOSTER commented on src/scenes/Interview/InterviewEdit.jsx
> +  const id_campaign = reduxState.Campaign.current_campaign;
Utilise le camelCase dans les composants
Le snake_case est réservé au document mongon (Model) ou au json stocker dans le localstorage

2021-04-19 13:30 UTC, RomainDECOSTER commented on src/scenes/Interview/InterviewForm.jsx
> +            <TextInput
Il est possible un texte Area ? ca leur montrera qu'ils peuvent écrire plus d'une ligne

2021-04-19 13:30 UTC, RomainDECOSTER commented on src/scenes/Interview/InterviewList.jsx
> +  function getCampaignName(id) {
Mets cette fonction dans les utils des campaign comme ca si on veut s'en servir autre part ca sera simple

2021-04-19 13:30 UTC, RomainDECOSTER commented on src/scenes/Interview/InterviewList.jsx
> +  function getPorfilNames(id, type) {
Mets cette function dans les utils de student et volunteer (ou en comon selon le plus simple)

2021-04-19 13:30 UTC, RomainDECOSTER commented on src/scenes/Interview/InterviewList.jsx
> +                interviewed_id: interviewed_id,
Idem utilise le camelCase

2021-04-19 13:30 UTC, RomainDECOSTER commented on src/scenes/Interview/components/InterviewSubmitButton.jsx
> +    console.log(fields);
Supprime les console log

2021-04-19 13:30 UTC, RomainDECOSTER commented on src/services/comon/utils.js
> +      students: await StudentActioner.list(id_campaign),
Pareil ici, il est préférable d'utiliser le camelCase

2021-04-19 13:36 UTC, FoucaultChdr commented on src/scenes/Home/components/InterviewDialogBox.jsx
> +                className="bosch-sensor-edit-button"
Je sais pas je l'ai choper danss ton submit buttons pour avoir une cohérence graphique

2021-04-19 14:14 UTC, RomainDECOSTER commented on src/scenes/Home/components/InterviewDialogBox.jsx
> +                className="bosch-sensor-edit-button"
Test si elle existe avec CTRL+MAJ+F et si elle existe tu peux changer le nom, parce que bosch pas sur qu'on en est un jour dans notre plateforme ;)

2021-04-20 08:38 UTC, RomainDECOSTER requested changes

2021-04-20 08:38 UTC, RomainDECOSTER commented on src/scenes/Student/StudentEdit.jsx
> +        console.log(infos);
A supprimer

2021-04-20 08:38 UTC, RomainDECOSTER commented on src/services/campaign/utils.js
> +    return templates.campaigns.find(element => element._id === id).name;
Tu peux retourner un string par défaut si `templates.campaigns.find(element => element._id === id) === undefined` tu peux même essayer ce que j'ai dit hier 
`templates.campaigns.find(element => element._id === id)?.name || "Campagne inconnue"`

2021-04-20 08:38 UTC, RomainDECOSTER commented on src/services/campaign/utils.js
> +    return templates.campaigns.find(element => element._id === id).name;
Je sais pas si ca va fonctionner ^^

2021-04-20 08:38 UTC, RomainDECOSTER commented on src/services/comon/utils.js
> +      const item = templates.students.find(element => element._id === idProfil);
Pareil si item === undefined quand tu fais `item.gene...` ca va planter

2021-04-20 08:38 UTC, RomainDECOSTER commented on src/services/comon/utils.js
> +      const item = templates.students.find(element => element._id === idProfil);
Et au lieu d'envoyer tout les templates tu peux juste envoyer vonlunteers ou student:
```
getPorfilNames(idProfil, entities){
const item = entities.find(....)
}
```

2021-04-20 08:58 UTC, FoucaultChdr commented on src/services/campaign/utils.js
> +    return templates.campaigns.find(element => element._id === id).name;
Tester et approuvé !

2021-04-20 08:59 UTC, RomainDECOSTER commented on src/services/campaign/utils.js
> +    return templates.campaigns.find(element => element._id === id).name;
Nice

2021-04-20 13:58 UTC, RomainDECOSTER approved these changes

2021-04-20 13:58 UTC, merged